version: '3.7'
#
services:
  iris:
    build:
      context: ./build
      args:
        COMMIT_ID: ${COMMIT_ID}
    image: dpmeister/simple
    hostname: myiris
    command:
      --check-caps false

    ports:
    # superserver default port 
    - "1972:1972"
    # webserver/management portal port
    - "52773:52773"

    volumes:
    # ISC = InterSystems IRIS install dir
    - ./external-vol-mgr:/iris-mgr
    - ./external-vol-db:/vol-data
    - ./cos:/home/irisowner/cos
    - ./UserCPF:/home/irisowner/cpf

    environment:
    - TZ=JST-9
    #; comment out this line to disable durable sys
    - ISC_DATA_DIRECTORY=/iris-mgr/IRIS_conf.d
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
