version: '3.7'
#
services:
  irissvc:
    build:
      context: ./build
      args:
        COMMIT_ID: ${COMMIT_ID}
    image: dpmeister/irisdemo:simple
    init: true
    hostname: myiris

    ports:
    # superserver default port 
    - "51773:51773"
    # webserver/management portal port
    - "52773:52773"

    volumes:
    # ISC = InterSystems IRIS install dir
    - external-vol-mgr:/iris-mgr
    - external-vol-db:/vol-data

    environment:
    - TZ=JST-9
    - ISC_DATA_DIRECTORY=/iris-mgr/IRIS_conf.d

volumes:
       external-vol-mgr:
       external-vol-db:
