services:
  iris:
    depends_on:
      - iris-init
      - webgateway
    build:
      context: ./build
      args:
        COMMIT_ID: ${COMMIT_ID}
    image: dpmeister/simple
    hostname: iris
    command: --ISCAgent false --monitorCPF false
    ports:
    # superserver default port 
    - "1972:1972"

    volumes:
    # ISC = InterSystems IRIS install dir
    - ./external-vol-mgr:/iris-mgr
    - ./external-vol-db:/vol-data
    - ./cos:/home/irisowner/cos
    - ./UserCPF:/home/irisowner/cpf

    environment:
    - TZ=JST-9
    #; comment out this line to disable durable sys
    - ISC_DATA_DIRECTORY=/iris-mgr/IRIS_conf.d
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf

  iris-init:
    command: 'chown -R 51773:51773 /iris-mgr /vol-data'
    image: busybox
    volumes:
    - ./external-vol-mgr:/iris-mgr
    - ./external-vol-db:/vol-data

  webgateway:
    image: containers.intersystems.com/intersystems/webgateway:2024.1
    init: true
    container_name: webgateway
    hostname: webgateway
    ports:
    - "8882:80"
    - "8883:443"
    environment:
    #- ISC_DATA_DIRECTORY=/webgateway-shared/durable
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - ./webgateway:/webgateway-shared
