apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: iris-merge-cpf
data:
  merge.cpf: |-
    [Startup]
    SystemMode=TEST
    WebServer=1
    PasswordHash=FBFE8593AEFA510C27FD184738D6E865A441DE98,u4ocm4qh

    [config]
    globals=0,0,32,0,0,0
    routines=32

    [Actions]
    CreateDatabase:Name=MYAPP-DATA-EXT,Directory=/vol-data/MYAPP-DATA
    ModifyNamespace:Name=MYAPP,Globals=MYAPP-DATA-EXT,Routines=MYAPP-CODE

---
apiVersion: v1
kind: Service
metadata:
  name: iris
  labels:
    app: iris
spec:
  type: LoadBalancer
  selector:
    app: iris
  ports:
  - protocol: TCP
    port: 52773
    targetPort: 52773
---

apiVersion: v1
kind: Service
metadata:
  name: iris
  labels:
    app: iris
spec:
  ports:
  - port: 52773
    protocol: TCP
    name: http
  clusterIP: None # Headless Service
  selector:
    app: iris
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data
spec:
  selector:
    matchLabels:
      app: iris
  serviceName: "iris"
  replicas: 1
  template:
    metadata:
      labels:
        app: iris
    spec:
      securityContext: 
        fsGroup: 52773
      containers:
      - name: iris
        image: dpmeister/simple:latest
        ports:
        - containerPort: 1972
        - containerPort: 52773
        env:
        - name: ISC_CPF_MERGE_FILE
          value: /irissys/cpf/merge.cpf
        - name: ISC_DATA_DIRECTORY
          value: /iris-mgr/IRIS_conf.d
        - name: TZ
          value: JST-9
        volumeMounts:
        - mountPath: /irissys/cpf/
          name: iris-cpf
        - mountPath: /iris-mgr
          name: dbv-mgr
        - mountPath: /vol-data
          name: dbv-data
      volumes:
      - configMap:
          defaultMode: 420
          name: iris-merge-cpf
        name: iris-cpf
  volumeClaimTemplates:
  - metadata:
      name: dbv-mgr
      labels:
        app: iris
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: microk8s-hostpath
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: dbv-data
      labels:
        app: iris
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: microk8s-hostpath
      resources:
        requests:
          storage: 1Gi