apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: iris-merge-cpf
data:
  merge.cpf: |-
    [Startup]
    SystemMode=TEST
    WebServer=1

    [config]
    globals=0,0,32,0,0,0
    routines=32

    [Actions]
    CreateDatabase:Name=MYAPP2-DATA,Directory=/vol-data/MYAPP2-DATA
    ModifyNamespace:Name=MYAPP,Globals=MYAPP2-DATA,Routines=MYAPP-CODE

---
apiVersion: v1
kind: Service
metadata:
  name: iris
  labels:
    app: my-iris
spec:
  type: LoadBalancer
  ports:
  - port: 52773
    targetPort: 52773
    protocol: TCP
    name: http
  selector:
    app: my-iris
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iris
spec:
  selector:
    matchLabels:
      app: my-iris
  serviceName: "my-iris"
  replicas: 1
  template:
    metadata:
      labels:
        app: my-iris
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: iris
        #image: containers.intersystems.com/intersystems/iris-community:2022.2.0.293.0
        #image: dpmeister/simple
        image: localhost:32000/simple
        imagePullPolicy: "Always"
        ports:
        - containerPort: 1972
        - containerPort: 52773
        env:
        - name: ISC_CPF_MERGE_FILE
          value: /irissys/cpf/merge.cpf
        - name: ISC_DATA_DIRECTORY
          value: /iris-mgr/IRIS_conf.d
        - name: TZ
          value: JST-9
        volumeMounts:
        - mountPath: /irissys/cpf/
          name: iris-cpf
        - mountPath: /iris-mgr/IRIS_conf.d
          name: dbv-mgr
        - mountPath: /vol-data
          name: dbv-data
      volumes:
      - configMap:
          defaultMode: 420
          name: iris-merge-cpf
        name: iris-cpf
  volumeClaimTemplates:
  - metadata:
      name: dbv-mgr
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: microk8s-hostpath
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: dbv-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: microk8s-hostpath
      resources:
        requests:
          storage: 1Gi